name: Question
description: Ask a question, related to this list or it's content
title: '[QUESTION] <title>'
labels: ['Question']
assignees:
  - AdamXweb
body:

  # Question Input
  - type: textarea
    id: question
    attributes:
      label: Your Question
    validations:
      required: true

  # Confirmation checkboxes
  - type: checkboxes
    id: idiot-check
    attributes:
      label: Please tick the boxes
      description: Before submitting, please ensure that
      options:
        - label: You have filled out this form accurately, and to the best of your knowledge
          required: true
        - label: You have indicated weather or not you are associated with this project or a competitor
          required: true
        - label: A similar submission has not already [been opened](https://github.com/AdamXweb/awesome-aussie/issues?q=is%3Aissue) for this software/ service
          required: true
        - label: The item is on the [Airtable master list](https://airtable.com/shruokTjBBXkElK4n)
          required: true
        - label: You agree to the [code of conduct](https://github.com/AdamXweb/awesome-aussie/blob/master/.github/CODE_OF_CONDUCT.md)
          required: true
  
  # Final message
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
        <img align="left" width="160" src="https://media.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif" alt="👾" />
        Thank you for your suggested removal! You should expect a reply within 48 hours.<br>
        ⭐️ Consider dropping the repo a star if you're enjoying Awesome Aussie.<br>
    validations:
      required: false