name: Sync Github Issues to Baserow

on:
  workflow_dispatch:
  schedule:
    # Hourly
    - cron: "0 * * * *"

jobs:
  syncissues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Verify Baserow issue table
        run: pnpm run check-schema
        env:
          BASEROW_API_TOKEN: ${{ secrets.BASEROW_API_TOKEN }}
          BASEROW_API_BASE_URL: ${{ secrets.BASEROW_API_BASE_URL }}
          BASEROW_PROVIDERS_TABLE_ID: ${{ secrets.BASEROW_PROVIDERS_TABLE_ID }}
          BASEROW_GITHUB_ISSUES_TABLE_ID: ${{ secrets.BASEROW_GITHUB_ISSUES_TABLE_ID }}

      - name: Sync Github issues into Baserow
        run: pnpm run issues
        env:
          BASEROW_API_TOKEN: ${{ secrets.BASEROW_API_TOKEN }}
          BASEROW_API_BASE_URL: ${{ secrets.BASEROW_API_BASE_URL }}
          BASEROW_GITHUB_ISSUES_TABLE_ID: ${{ secrets.BASEROW_GITHUB_ISSUES_TABLE_ID }}
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
          GH_OWNER: AdamXweb
          GH_REPO: awesome-aussie
