name: Add Issues to Airtable from Github

on:
  workflow_dispatch: # Manual dispatch
  schedule:
    # Hourly
    - cron: "0 * * * *"

jobs:
  syncissues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - name: Syncing Issues from Github to Airtable
        run: npm run issues
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_ID_ISSUES: ${{ secrets.AIRTABLE_TABLE_ID_ISSUES }}
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
      - name: Add Issues To GitHub projects
        uses: actions/add-to-project@v0.3.0
