# Pushes the contents of the repo to the Codeberg mirror
name: Mirror to Codeberg
on:
  push:
    branches: [ 'main', 'airtable' ]    
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 6 * * 3'
jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: "git@codeberg.org:adamxweb/awesome-aussie.git"
          ssh_private_key: ${{ secrets.BOT_SSH }}